version: "3.7"

services:
  lab:
    build:
      context: .
    volumes:
      - ./src:/app
    ports:
      - "8888:8888"
    command:
      [jupyter-lab, --no-browser, --ip=0.0.0.0, --allow-root, --port=8888]